---
# configure-local-storage default vars

# controlplane_* configures local storage on SNO, 3-Node Compact MNO, and
# Control-plane nodes on a "standard" multi-node deployment with workers
controlplane_etcd_on_nvme: false
controlplane_nvme_device: /dev/nvme0n1
controlplane_localstorage_configuration: false
controlplane_localstorage_device: /dev/sdb
controlplane_localstorage_lv_count: 10
controlplane_localstorage_lv_size: 100G

# worker_* configures local storage on worker nodes on a "standard"
# multi-node deployment with workers
worker_localstorage_configuration: false
worker_localstorage_device: /dev/nvme0n1
worker_localstorage_lv_count: 10
worker_localstorage_lv_size: 100G

localvolume2_configuration: false
localvolume2_device: /dev/sdc
