---
# Create and deploy a cluster with the Assisted Installer
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/mno-deploy.yml
#

- name: Adds nodes to a cluster
  hosts: bastion
  vars_files:
  - vars/lab.yml
  - vars/all.yml
  roles:
  - validate-vars
  - ocp-release
  - role: boot-iso
    vars:
      inventory_group: new_workers
      index: "{{ worker_node_count }}"
      virtual_media_iso: "day2add.iso"