---
- name: Adds nodes to a cluster
  hosts: bastion
  vars_files:
  - vars/lab.yml
  - vars/all.yml
  - vars/scale_out.yml
  roles:
  - ocp-scale-out
  - role: boot-iso
    vars:
      inventory_group: 'worker'
      offset: "{{ current_worker_count }}"
      index: "{{ current_worker_count+scale_out_count }}"
      virtual_media_iso: "ocp-scale-out.x86_64.iso"
  - ocp-scale-out-csr
